name: Secrets Scan Workflow
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
permissions:
  contents: read
  pull-requests: write
  security-events: read
jobs:
  secrets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 10  # Only fetch the last 10 commits

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      - name: Run TruffleHog (Last 10 Commits)
        id: trufflehog-scan
        run: |
          # Run TruffleHog on the last 10 commits
          trufflehog --regex --json . > trufflehog_results.json
          # Check if the results file is not empty
          if [ -s trufflehog_results.json ]; then
            echo "::error::Secrets found! Check the TruffleHog results."
            exit 1
          else
            echo "No secrets found."
          fi

      - name: TruffleHog OSS
        id: trufflehog-oss
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          extra_args: --debug

      - name: Scan Results Status
        if: steps.trufflehog-oss.outcome == 'failure'
        run: exit 1

      - name: Process TruffleHog Results
        if: failure() && steps.trufflehog-scan.outcome == 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          REPO_NAME=${{ github.repository }}
          RUN_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          if [ -s trufflehog_results.json ]; then
            results=$(jq -r --arg REPO_NAME "$REPO_NAME" --arg RUN_DATE "$RUN_DATE" \
              '. | "\n\n\nRepository: \($REPO_NAME)\nRun Date: \($RUN_DATE)\nCommit: \(.commit)\nCommit Hash: \(.commitHash)\nPath: \(.path)\nReason: \(.reason)"' trufflehog_results.json)
            if [ -n "$results" ]; then
              message=":siren: *Secrets Found!* ${results}"
              echo "$message" > trufflehog_message.txt
              curl -X POST -H 'Content-type: application/json' \
                --data "$(jq -n --arg text "$message" '{"text": $text}')" \
                "$SLACK_WEBHOOK_URL"
            fi
          fi

      - name: Add TruffleHog Results as PR Comment
        if: failure() && steps.trufflehog-scan.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const message = fs.readFileSync('trufflehog_message.txt', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
